# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vid_chains',
                'doc_host': 'https://DreamAIIO.github.io',
                'git_url': 'https://github.com/DreamAIIO/vid_chains',
                'lib_path': 'vid_chains'},
  'syms': {'vid_chains.core': {'vid_chains.core.foo': ('core.html#foo', 'vid_chains/core.py')}}}
