# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vid_chains',
                'doc_host': 'https://DreamAIIO.github.io',
                'git_url': 'https://github.com/DreamAIIO/vid_chains',
                'lib_path': 'vid_chains'},
  'syms': { 'vid_chains.api': { 'vid_chains.api.FastAPIDeployment': ('apis.html#fastapideployment', 'vid_chains/api.py'),
                                'vid_chains.api.FastAPIDeployment.image_file': ( 'apis.html#fastapideployment.image_file',
                                                                                 'vid_chains/api.py'),
                                'vid_chains.api.FastAPIDeployment.image_path': ( 'apis.html#fastapideployment.image_path',
                                                                                 'vid_chains/api.py'),
                                'vid_chains.api.Image_Data': ('apis.html#image_data', 'vid_chains/api.py')},
            'vid_chains.core': {},
            'vid_chains.imports': {},
            'vid_chains.utils': { 'vid_chains.utils.detect_objects': ('utils.html#detect_objects', 'vid_chains/utils.py'),
                                  'vid_chains.utils.inter_dist': ('utils.html#inter_dist', 'vid_chains/utils.py'),
                                  'vid_chains.utils.load_obj_model': ('utils.html#load_obj_model', 'vid_chains/utils.py')}}}
